### ISSUE TITLE
Don't report error when missing the last '}'

### ISSUE THREAD

**Issue by ruowan** [ts-common/json-parser#11]
json-parser don't report errors when parsing missing the last parentheses.

**Comment by ruowan** [comment]
I found a bug in ts-common/json-parser repo. When the json file missing the last bracket. The json-parser don’t report error. For example, 
`{“name”: “bob”`  
json-parser can’t report any error about the invalid json format. Could you please help me to fix the bug?

**Comment by sergey-shandar** [comment]
@ruowan I would suggest to create a test case first https://github.com/ts-common/json-parser/blob/master/src/test/parserTests.ts

**Comment by ruowan** [comment]
https://github.com/ts-common/json-parser/pull/12 I create a PR to add a test case. and also format the code

**Comment by jianyexi** [comment]
When missing the first bracket , the json-parser don’t report error too .
e.g.
{get":  // missing {
        "tags": [
          "Applications"
        ]
     }

**Comment by ruowan** [comment]
closed. The 0.9.0 has fixed it
